# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: eccs-labs
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: clinical
# "service" is the name of this project. This will also be added to your AWS resource names.
service: clinical-backend

plugins:
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8080

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    seed:
      local:
        sources:
          - table: usersTable

  s3:
    bucket: my-bucket
    region: us-east-1
    host: localhost
    port: 4599
    accessKey: "ACCESS_KEY"
    secretKey: "SECRET_KEY"

# stages:
#   default:
#     params:
#       tableName: "users-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
  # environment:
  #   USERS_TABLE: ${param:tableName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
    timeout: 300
  auth:
    handler: handler.handler
    events:
      - httpApi: "POST /api/auth/signin"
      - httpApi: "POST /api/auth/signup"
      - httpApi: "POST /api/auth/send-otp"
      - httpApi: "POST /api/auth/reset-password"
      - httpApi: "POST /api/auth/update-password"
      - httpApi: "GET /api/auth/users"
  cases:
    handler: handler.handler
    events:
      - httpApi: "GET /api/case/details/{proxy+}"
      - httpApi: "GET /api/case/all/"
      - httpApi: "GET /api/case/ongoing-case/"
      - httpApi: "POST /api/case/add"
      - httpApi: "POST /api/case/update/{proxy+}"
      - httpApi: "POST /api/case/duplicate"
      - httpApi: "POST /api/case/publish/"
      - httpApi: "POST /api/case/add/feedback/"
      - httpApi: "GET /api/case/feedbacks/{proxy+}"
      - httpApi: "GET /api/case/responses/{proxy+}"
      - httpApi: "GET /api/case/data/{proxy+}"
      - httpApi: "GET /api/case/student/attempts/{proxy+}"
      - httpApi: "DELETE /api/case/delete-case/{proxy+}"
      - httpApi: "DELETE /api/case/delete/all/"
  quiz:
    handler: handler.handler
    events:
      - httpApi: "POST /api/quiz/submit"
      - httpApi: "GET /api/quiz/answers/{proxy+}"
  student:
    handler: handler.handler
    events:
      - httpApi: "GET /api/student/certificates"
      - httpApi: "GET /api/student/certificate/{proxy+}"

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    LocalBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: local-bucket
