/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Answers": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Cases": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Certificates": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Feedback": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MyApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "NEXT_JWT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_NODE_ENV": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PASS_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PASS_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_BASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StudentCaseAttempts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Users": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
