/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "APS_ACCESS_CODE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "APS_MERCHANT_IDENTIFIER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "APS_SHA_REQUEST_PHRASE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "APS_SHA_RESPONSE_PHRASE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CaseMaterials": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Certificates": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ECCSEMAIL": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "Feedback": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "HASH_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_BASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_DOMAIN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_NODE_ENV": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Payments": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SUBSCRIPTION_FEE_AED": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StudentsResponses": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "TeacherCaseStudies": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "eccs": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "eccslabs": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "eccslabsClient": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "localdev.eccswebclient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}

import "sst"
export {}