/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CaseMaterials": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Certificates": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ECCSEMAIL": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "Feedback": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "NEXT_PUBLIC_BASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_DOMAIN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_NODE_ENV": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_PASS_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StudentsResponses": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "TeacherCaseStudies": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "eccs": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "eccslabs": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "eccslabsClient": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "localdev.eccswebclient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}