name: Deploy SST App to Staging

on:
  push:
    branches:
      - staging

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Get OIDC Token
        id: get-oidc-token
        run: |
          OIDC_TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
          echo "OIDC_TOKEN=$OIDC_TOKEN" >> $GITHUB_ENV
          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN" >> $GITHUB_ENV

      - name: Debug OIDC Token
        run: |
          echo "OIDC_TOKEN=${{ env.OIDC_TOKEN }}"
          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN=${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Install SST CLI
        run: npm install -g sst

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh-deployment-stg
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Staging
        run: sst deploy --stage staging
