name: Deploy SST App to Staging

on:
  push:
    branches:
      - staging

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  AWS_REGION: me-south-1
  NEXT_PUBLIC_NODE_ENV: staging
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  NEXT_JWT_SECRET: ${{ secrets.NEXT_JWT_SECRET }}
  NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
  NEXT_PUBLIC_PASS_SECRET_KEY: ${{ secrets.NEXT_PUBLIC_PASS_SECRET_KEY }}

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/gh-actions-staging
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Staging
        run: npx sst deploy --stage preproduction

      # - name: Cache Next Build
      #   uses: actions/cache@v4
      #   with:
      #     # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
      #     path: |
      #       ~/.npm
      #       ${{ github.workspace }}/.next/cache
      #     # Generate a new cache whenever packages or source files change.
      #     key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
      #     # If source files changed but packages didn't, rebuild from a prior cache.
      #     restore-keys: |
      #       ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
