# name: Deploy SST App to Staging

# on:
#   push:
#     branches:
#       - staging

# permissions:
#   id-token: write # This is required for requesting the JWT
#   contents: read # This is required for actions/checkout

# env:
#   AWS_REGION: us-east-1
#   NEXT_PUBLIC_NODE_ENV: staging
#   AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
#   NEXT_JWT_SECRET: ${{ secrets.NEXT_JWT_SECRET }}
#   NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
#   NEXT_PUBLIC_PASS_SECRET_KEY: ${{ secrets.NEXT_PUBLIC_PASS_SECRET_KEY }}

# jobs:
#   deploy:
#     environment: staging
#     runs-on: ubuntu-latest

#     steps:
#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: "20"

#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Install dependencies
#         run: npm install

#       - name: Install SST CLI
#         run: npm install -g sst

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/gh-deployment-stg
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Deploy to Staging
#         run: sst deploy --stage staging
